title: Repository of articles on Covid-19 by the Fight Aids Foundation STI unit
url: "https://carlosjoserg.github.io"
baseurl: ""

markdown: kramdown
ins_logo: "./logo_en.png"

tracking_id: #

footer: yes
footer_url: "https://www.flsida.org/"
footer_text: "Copyright 2020 Fight AIDS and Infectious Diseases Foundation"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Publications"
   link: "."
 - name: "About"
   link: "flsida"
 - name: "Contact"
   link: "contact"
